<?php

namespace AppBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByWildStarName($search)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM AppBundle:Event a WHERE a.name LIKE :string OR a.description LIKE :string ORDER BY a.dateStart ASC'
            )
            ->setParameter('string', '%'.$search.'%')
            ->getResult();
    }
}
